image:
  repository: github.com/mohitkumar/orchy
  tag: 1.0.0
  pullPolicy: IfNotPresent
serfPort: 8401
rpcPort: 8400
httpPort: 8080
replicas: 3
partitions: 71
redisHost: my-release-redis-cluster.default.svc.cluster.local
redisPassword: lp9pZnj2Xl
redisPort: 6379
service:
  lb: true