image:
  repository: github.com/mohitkumar/orchy
  tag: 1.0.0
  pullPolicy: IfNotPresent
serfPort: 8401
rpcPort: 8400
httpPort: 8080
replicas: 3
partitions: 71
redisHost: redis-host
redisPort: 6379
service:
  lb: true