apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "orchy.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: serf-tcp
      protocol: "TCP"
      port: {{ .Values.serfPort }}
      targetPort: serf
    - name: serf-udp
      protocol: "UDP"
      port: {{ .Values.serfPort }}
      targetPort: serf
  selector: {{ include "orchy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchy.fullname" . }}-rpc
  namespace: {{ .Release.Namespace }}
  labels: {{ include "orchy.labels" . | nindent 4 }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.rpcPort }}
      targetPort: rpc
  selector: {{ include "orchy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchy.fullname" . }}-rest
  namespace: {{ .Release.Namespace }}
  labels: {{ include "orchy.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
  selector: {{ include "orchy.selectorLabels" . | nindent 4 }}  