# START: annotations
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orchy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "orchy.labels" . | nindent 4 }}
  {{ if .Values.service.lb }}
  annotations:
    service-per-pod-label: "statefulset.kubernetes.io/pod-name"
    service-per-pod-ports: "{{.Values.rpcPort}}:{{.Values.serfPort}}:{{.Values.httpPort}}"
  {{ end }}
spec:
  selector:
    matchLabels: {{ include "orchy.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "orchy.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "orchy.fullname" . }}
      labels: {{ include "orchy.labels" . | nindent 8 }}
    spec:
      initContainers:      
      - name: {{ include "orchy.fullname" . }}-config-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command:          
          - /bin/sh
          - -c
          - |-
            ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
            cat > /var/run/orchy/config.yaml <<EOD
            partitions: {{.Values.partitions}}
            grpc-port: {{.Values.rpcPort}}
            rpc-port: {{.Values.rpcPort}}
            http-port: {{.Values.httpPort}}
            node-name: "$HOSTNAME.orchy.{{.Release.Namespace}}.svc.cluster.local"
            bind-address: "$HOSTNAME.orchy.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"
            redis-address: {{.Values.redisHost}}
            redis-password: {{.Values.redisPassword}}
            $([ $ID != 0 ] && echo 'cluster-address: "orchy-0.orchy.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"')
            EOD
        volumeMounts:
        - name: datadir
          mountPath: /var/run/orchy
      containers:
      - name: {{ include "orchy.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rpcPort }}
          name: rpc
        - containerPort: {{ .Values.serfPort }}
          name: serf
        - containerPort: {{ .Values.httpPort }}
          name: http 
        args:
          - --config-file=/var/run/orchy/config.yaml
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
          initialDelaySeconds: 10
        volumeMounts:
        - name: datadir
          mountPath: /var/run/orchy   
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}    